(package "8comic" "0.0.1" "Use 8comic to read manga")

(website-url "https://github.com/jcs-elpa/8comic")
(keywords "comic" "manga" "read" "reader")

(package-file "8comic.el")

(source "melpa")

(depends-on "emacs" "24.4")
(depends-on "request")

(setq network-security-level 'low      ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
      byte-compile-error-on-warn nil)
